package Farkle;

import javax.swing.*;

/**
 *
 * @author johanreyes
 */
public class WelcomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form WelcomeFrame
     */
    public WelcomeFrame() {
        initComponents();
        playerTwo.setEnabled(false);
        playerThree.setEnabled(false);
        playerFour.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numPlayers = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        beginGameButton = new javax.swing.JButton();
        playerOne = new javax.swing.JTextField();
        playerTwo = new javax.swing.JTextField();
        playerThree = new javax.swing.JTextField();
        playerFour = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Welcome to Card Farkle");

        numPlayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Player", "2 Players", "3 Players", "4 Players" }));
        numPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPlayersActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Player names");

        beginGameButton.setText("Begin Game");
        beginGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginGameButtonActionPerformed(evt);
            }
        });

        playerOne.setText("Player 1");

        playerTwo.setText("Player 2");

        playerThree.setText("Player 3");

        playerFour.setText("Player 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(beginGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(numPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playerOne)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playerTwo)
                    .addComponent(playerThree)
                    .addComponent(playerFour, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(beginGameButton)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPlayersActionPerformed
        playaz = (String) numPlayers.getSelectedItem();
        
         if(playaz.equals("1 Player"))
        {
            numOfPlayers = 1;
            playerTwo.setEnabled(false);
            playerThree.setEnabled(false);
            playerFour.setEnabled(false);
        }
        if(playaz.equals("2 Players"))
        {
            numOfPlayers = 2;
            playerTwo.setEnabled(true);
            playerThree.setEnabled(false);
            playerFour.setEnabled(false);
        }
        if(playaz.equals("3 Players"))
        {
            numOfPlayers = 3;
            playerTwo.setEnabled(true);
            playerThree.setEnabled(true);
            playerFour.setEnabled(false);
        }
        if(playaz.equals("4 Players"))
        {
            numOfPlayers = 4;
            playerTwo.setEnabled(true);
            playerThree.setEnabled(true);
            playerFour.setEnabled(true);
        }
    }//GEN-LAST:event_numPlayersActionPerformed

    private void beginGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginGameButtonActionPerformed
        arrayNames();
        this.dispose();
        GameFrame gf = new GameFrame(namesOfPlayers);
        gf.setVisible(true);
        gf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        gf.pack();
    }//GEN-LAST:event_beginGameButtonActionPerformed

    public String[] arrayNames()
    {
        namesOfPlayers = new String[numOfPlayers];
        
        if(numOfPlayers == 1)
        {
            namesOfPlayers[0] = playerOne.getText();
        }
        if(numOfPlayers == 2)
        {
            namesOfPlayers[0] = playerOne.getText();
            namesOfPlayers[1] = playerTwo.getText();
        }
        if(numOfPlayers == 3)
        {
            namesOfPlayers[0] = playerOne.getText();
            namesOfPlayers[1] = playerTwo.getText();
            namesOfPlayers[2] = playerThree.getText();
        }
        if(numOfPlayers == 4)
        {
            namesOfPlayers[0] = playerOne.getText();
            namesOfPlayers[1] = playerTwo.getText();
            namesOfPlayers[2] = playerThree.getText();
            namesOfPlayers[3] = playerFour.getText();
        }
        
        return namesOfPlayers;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beginGameButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> numPlayers;
    private javax.swing.JTextField playerFour;
    private javax.swing.JTextField playerOne;
    private javax.swing.JTextField playerThree;
    private javax.swing.JTextField playerTwo;
    // End of variables declaration//GEN-END:variables

    private int numOfPlayers = 1;
    private String playaz;
    
    private String[] namesOfPlayers;
}
